---
title: "MODELOS LINEARES GENERALIZADOS   STA13829"
subtitle: "Plano de Ensino"
author: "Nátaly A. Jiménez Monroy"
institute: "LECON/DEST - UFES"
format: 
  revealjs:
    theme: moon
editor: visual
incremental: true  
---

# Plano de Ensino {transition="fade" transition-speed="slow"}

------------------------------------------------------------------------

**Horário:** Seg - Qua / 07:00h - 09:00h

**Ementa:** Definição - ligações canônicas - função desvio - métodos de estimação - testes de hipóteses - técnicas de diagnóstico – Aplicações - Modelos para dados binários - Modelos para dados de contagem - Modelos de dose-resposta - Modelos para tabelas de contingência - Aplicações.

------------------------------------------------------------------------

## Objetivos

-   Apresentar conceitos introdutórios de modelos lineares generalizados em um enfoque computacional;

-   Estudar a metodologia de modelos lineares generalizados, métodos de estimação, discutir a construção dos testes de hipóteses e técnicas de diagnóstico;

-   Aplicar as metodologias apresentadas por meio do uso de programas computacionais estatísticos.

. . .

**Pré-requisitos:** STA13824 ANÁLISE DE REGRESSÃO

------------------------------------------------------------------------

# Programa {transition="fade" transition-speed="fast"}

------------------------------------------------------------------------

-   INTRODUÇÃO

    -   Família Exponencial

-   MODELO LINEAR GENERALIZADO

    -   Conceito;
    -   Função de ligação;
    -   Função desvio;
    -   Função escore;
    -   Matriz de Informação;
    -   Estimação;
    -   Testes de hipóteses: Escore, Wald, Razão de verossimilhanças.

------------------------------------------------------------------------

-   MODELO LINEAR NORMAL

-   TÉCNICAS DE DIAGNÓSTICO E QUALIDADE DO AJUSTE

    -   Tipos de resíduo;
    -   Pontos de alavanca;
    -   Pontos influentes;
    -   Pontos aberrantes;
    -   Envelope.

------------------------------------------------------------------------

-   MODELOS PARA DADOS BINÁRIOS

    -   Modelos logísticos;
    -   Modelos de dose-resposta;
    -   Modelos de retas paralelas.

-   MODELOS PARA DADOS DE CONTAGEM

    -   Modelos de Poisson;
    -   Modelos com resposta binomial negativa;
    -   Sobredispersão;
    -   Introdução à modelagem para tabelas de contingência.
    
------------------------------------------------------------------------

-   MODELOS ADICIONAIS

    -   Modelos para dados assimétricos;
    -   Introdução a modelos de quase-verossimilhança.

------------------------------------------------------------------------

# Bibliografia Básica

------------------------------------------------------------------------

-   PAULA, Gilberto A. Modelos de regressão com apoio computacional. São Paulo: IME/USP, 2013. Disponível gratuitamente em: https://www.ime.usp.br/\~giapaula/texto_2024.pdf

-   MCCULLAGH, Peter; NELDER, John A. Generalized linear models. 2nd ed. Boca Raton: Chapman & Hall, 1989. 511 p.

-   DOBSON, Annette J. An introduction to generalized linear models. 2nd ed. Boca Raton, Fla.: Chapman & Hall/CRC, 2002.

. . .

**Observação:** Consultar a bibliografía complementar no Plano de Ensino.

------------------------------------------------------------------------

# Avaliação

------------------------------------------------------------------------

A avaliação consistirá de três provas escritas. A média final ($MF$) será calculada como a média aritmética das três provas.

. . .

**Observações**

-   Alunos que não obtiverem nota final igual ou superior a $7.0$ (sete) ao final do período letivo ficarão de prova final.

. . .

-   Independente da nota, o aluno que não tiver frequência igual ou superior a 75$\%$ será reprovado por faltas.

------------------------------------------------------------------------

# Datas importantes

------------------------------------------------------------------------

-   **Inicio das aulas:** Segunda-feira 21/10/2024

-   **Prova 1:** Segunda-feira 18/11/24

-   **Prova 2:** Segunda-feira 03/02/25

-   **Prova 3:** Segunda-feira 17/03/25

-   **Fim das aulas:** Segunda-feira 24/03/25

-   **Prova final:** Quarta-feira 26/03/25.
